config/routes.rb
Rails.application.routes.draw do

  root to: 'toppages#index'
  
  get 'signin-owner', to: 'owners#new'
  resources :owners, only: [:index, :show, :create, :edit, :update, :destroy]
  get 'signin-transporter', to: 'transporters#new'
  resources :transporters, only: [:index, :show, :create, :edit, :update, :destroy]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/owner.rb
class Owner < ApplicationRecord
  before_save {self.email.downcase!}

  validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true, confirmation: true, length: {maximum: 255},
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
    uniqueness: {case_sensitive: false}
  has_secure_password
  
end

app/models/transporter.rb
class Transporter < ApplicationRecord
  before_save {self.email.downcase!}
  validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true, confirmation: true, length: {maximum: 255},
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
    uniqueness: {case_sensitive: false}
  has_secure_password
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :require_login
  
  private
  def require_login
    unless logged_in_as_owner && logged_in_as_transporter
      flash[:warning] = "Please log in first, or sign in if you're new."
      redirect_to root_url
    end
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  
  def index
  end
  
  def show
    @owner = Owner.find(params[:id])
  end
  
  def new
    @owner = Owner.new
  end
  
  def create
    @owner = Owner.new(owner_params)
    if @owner.save
      flash[:success] = "Account registered successfully"
      redirect_to login_url(email: params[:owner][:email], password: params[:owner][:password])
    else
      flash.now[:danger] = "Sorry, something went wrong"
      render :new
    end
  end
  
  def edit
  end
  
  def update
  end
  
  def destroy
  end
  
  
  private
  
  def owner_params
    params.require(:owner).permit(:name, :email, :email_confirmation, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  
  def new
  end
  
  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    
    if login(email, password)
      flash[:success] = "Logged in successfully"
      redirect_to @user
    else
      flash[:danger] = 'Please verify your email address or password'
      render :new
    end
  end
  
  def destroy
    if session[:owner_id]
      session[:owner_id] = nil
      flash[:success] = 'Logged out'
      redirect_to root_url
    else
      session[:transporter_id] = nil
      flash[:success] = 'Logged out'
      redirect_to root_url
    end
  end
  
  
  private
  
  def login(email, password)
    @owner = Owner.find_by(email: email)
    @transporter = Transporter.find_by(email: email)
    if @owner && @owner.authenticate(password)
      session[:owner_id] = @owner.id
      @user = @owner
      return true
    elsif @transporter && @transporter.authenticate(password)
      session[:transporter_id] = @transporter.id
      @user = @transporter
      return true
    else
      return false
    end
  end
      
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  skip_before_action :require_login
  
  def index
  end
end

app/controllers/transporters_controller.rb
class TransportersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  
  def index
  end

  def show
    @transporter = Transporter.find(params[:id])
  end

  def new
    @transporter = Transporter.new
  end

  def create
    @transporter = Transporter.new(transporter_params)
    if @transporter.save
      flash[:success] = 'Account registered successfully'
      redirect_to login_path(email: params[:transporter][:email], password: params[:transporter][:password])
    else
      flash.now[:danger] = 'Sorry, something went wrong'
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  
  private
  
  def transporter_params
    params.require(:transporter).permit(:name, :email, :email_confirmation, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_owner
    @current_owner ||= Owner.find_by(id: session[:owner_id])
  end
  
  def current_transporter
    @current_transporter ||= Transporter.find_by(id: session[:transporter_id])
  end
  
  def logged_in_as_owner
    !!current_owner
  end
  
  def logged_in_as_transporter
    !!current_transporter
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/transporters_helper.rb
module TransportersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |m| %>
        <li><%= m %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navibar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-info py-3">
    <a class="navbar-brand" href="/">Matcher</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in_as_owner %>
          <li class="nav-item"><%= link_to 'Dashboard', owner_path(current_owner), class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Log out', logout_path, method: :delete, class: 'nav-link' %></li>
        <% elsif logged_in_as_transporter %>
          <li class="nav-item"><%= link_to 'Dashboard', transporter_path(current_transporter), class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Log out', logout_path, method: :delete, class: 'nav-link' %></li>
        <% else %>
          <%= link_to 'Log in', login_path, class: 'nav-item nav-link text-white' %>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>Matcher</title>
    
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://unpkg.com/jpncss@latest/dist/bootstrap/jpn.min.css">
  </head>

  <body class="h-100">
    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    
    <%= render 'layouts/navibar' %>
    <%= render 'layouts/flash_messages' %>
    
    <div class="container-fluid h-100">
      <%= yield %>
    </div>
  </body>
</html>

app/views/owners/new.html.erb
<div class="text-center mb-5">
  <h1>Sign in as Owner</h1>
</div>

<div class="row">
  <div class="col-sm-8 offset-sm-2">
    
    <%= form_with(model: @owner, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
    
      <div class="form-group row">
        <%= f.label :name, 'Your account name', class: 'col-sm-3' %>
        <%= f.text_field :name, class: 'form-control col-sm-9' %>
      </div>
      
      <div class="form-group row">
        <%= f.label :email, 'Email address', class: 'col-sm-3' %>
        <%= f.email_field :email, class: 'form-control col-sm-9' %>
        <%= f.email_field :email_confirmation, class: 'form-control col-sm-9 offset-sm-3 mt-3' %>
        <p class="col-sm-12 text-right">Please rewrite your email address for confirmation</p>
      </div>
      
      <div class="form-group row">
        <%= f.label :password, 'Password', class: 'col-sm-3' %>
        <%= f.password_field :password, class: 'form-control col-sm-9' %>
        <%= f.password_field :password_confirmation, class: 'form-control col-sm-9 offset-sm-3 mt-3' %>
        <p class="col-sm-12 text-right">Please rewrite your password for confirmation</p>
      </div>
      
      <%= f.submit 'Sign in', class: 'btn btn-primary col-sm-6 offset-sm-3' %>
    <% end %>
  </div>
</div>

app/views/owners/show.html.erb
<div class="text-left mb-5">
  <h2>Profile page</h2>
</div>

<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @owner.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="#" alt="<%= @owner.name %>">
      </div>
    </div>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="#" class="nav-link">Offers</a></li>
      <li class="nav-item"><a href="#" class="nav-link">Affairs in progress</a></li>
      <li class="nav-item"><a href="#" class="nav-link">Account information</a></li>
    </ul>
  </div>
</div>

app/views/toppages/index.html.erb
<% if logged_in_as_owner %>
  <p>Logged in as owner</p>

<% elsif logged_in_as_transporter %>
  <p>Logged in as transporter</p>
  
<% else %>
  <div class="row jumbotron h-100 py-3">
    <a href="<%= signin_owner_path %>" class="col-sm-6 text-center text-decoration-none text-info pt-5 h-100" style="border-right: 1px solid black;">
  
        <h1>Optimize your distribution</h1>
        <h3>by discovering transporters with us</h3>
  
    </a>
    <a href="<%= signin_transporter_path %>" class="col-sm-6 text-center text-decoration-none text-info pt-5 h-100">
        <h1>Maximize your trucking-asset-performance</h1>
        <h3>by discovering clients with us</h3>
    </a>
  </div>
<% end %>

app/views/transporters/edit.html.erb
<h1>Transporter#edit</h1>
<p>Find me in app/views/transporter/edit.html.erb</p>

app/views/transporters/index.html.erb
<h1>Transporter#index</h1>
<p>Find me in app/views/transporter/index.html.erb</p>

app/views/transporters/new.html.erb
<div class="text-center mb-5">
  <h1>Sign in as Transporter</h1>
</div>

<div class="row">
  <div class="col-sm-8 offset-sm-2">
    
    <%= form_with(model: @transporter, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
    
      <div class="form-group row">
        <%= f.label :name, 'Your account name', class: 'col-sm-3' %>
        <%= f.text_field :name, class: 'form-control col-sm-9' %>
      </div>
      
      <div class="form-group row">
        <%= f.label :email, 'Email address', class: 'col-sm-3' %>
        <%= f.email_field :email, class: 'form-control col-sm-9' %>
        <%= f.email_field :email_confirmation, class: 'form-control col-sm-9 offset-sm-3 mt-3' %>
        <p class="col-sm-12 text-right">Please rewrite your email address for confirmation</p>
      </div>
      
      <div class="form-group row">
        <%= f.label :password, 'Password', class: 'col-sm-3' %>
        <%= f.password_field :password, class: 'form-control col-sm-9' %>
        <%= f.password_field :password_confirmation, class: 'form-control col-sm-9 offset-sm-3 mt-3' %>
        <p class="col-sm-12 text-right">Please rewrite your password for confirmation</p>
      </div>
      
      <%= f.submit 'Sign in', class: 'btn btn-primary col-sm-6 offset-sm-3' %>
    <% end %>
  </div>
</div>

app/views/transporters/show.html.erb
<div class="text-left mb-5">
  <h2>Profile page</h2>
</div>

<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @transporter.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="#" alt="<%= @transporter.name %>">
      </div>
    </div>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="#" class="nav-link">Units</a></li>
      <li class="nav-item"><a href="#" class="nav-link">Affairs in progress</a></li>
      <li class="nav-item"><a href="#" class="nav-link">Account information</a></li>
    </ul>
  </div>
</div>